# CUDA_VISIBLE_DEVICES=0 python utils/llmasajudge_VGU.py --model_name Bagel --output_dir /hongbojiang/workdirs/LLM_judge/VGU
CUDA_VISIBLE_DEVICES=1 python utils/llmasajudge_VGU.py --model_name BLIP3o --output_dir /hongbojiang/workdirs/LLM_judge/VGU
CUDA_VISIBLE_DEVICES=2 python utils/llmasajudge_VGU.py --model_name Janus --output_dir /hongbojiang/workdirs/LLM_judge/VGU
CUDA_VISIBLE_DEVICES=3 python utils/llmasajudge_VGU.py --model_name JanusFlow --output_dir /hongbojiang/workdirs/LLM_judge/VGU
CUDA_VISIBLE_DEVICES=4 python utils/llmasajudge_VGU.py --model_name Show-o --output_dir /hongbojiang/workdirs/LLM_judge/VGU
CUDA_VISIBLE_DEVICES=5 python utils/llmasajudge_VGU.py --model_name UniLIP --output_dir /hongbojiang/workdirs/LLM_judge/VGU
# CUDA_VISIBLE_DEVICES=6 python utils/llmasajudge_VGU.py --model_name Qwen-Image --output_dir /hongbojiang/workdirs/LLM_judge/VGU
# CUDA_VISIBLE_DEVICES=7 python utils/llmasajudge_VGU.py --model_name LongCat --output_dir /hongbojiang/workdirs/LLM_judge/VGU
# CUDA_VISIBLE_DEVICES=7 python utils/llmasajudge_VGU.py --model_name VGT --output_dir /hongbojiang/workdirs/LLM_judge/VGU